In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np

In [7]:
a=np.array([1,2,3,4])
print(type(a))
print(a)
print(a.shape)
print(a.ndim)
print(a.size)

<class 'numpy.ndarray'>
[1 2 3 4]
(4,)
1
4


In [8]:
b=[[1,3,4],[5,8,9]]
a=np.array(b)
print(type(a))
print(a)
print(a.shape)
print(a.ndim)
print(a.size)

<class 'numpy.ndarray'>
[[1 3 4]
 [5 8 9]]
(2, 3)
2
6


In [10]:
#arange function
x=np.arange(1,10)
print(x)

[1 2 3 4 5 6 7 8 9]


In [11]:
x=np.arange(1,10,2)
print(x)

[1 3 5 7 9]


In [12]:
#linspace
x=np.linspace(1,10,20)
print(x)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [13]:
x=np.random.rand(2,8)
print(x)
print(x.ndim)
print(x.size)

[[0.0118889  0.61768269 0.28494071 0.89715962 0.57886732 0.95672824
  0.24231612 0.33070701]
 [0.51672958 0.46061073 0.65054856 0.42803534 0.76560216 0.14218218
  0.40288451 0.99522293]]
2
16


In [20]:
x=np.random.rand(2,8,10)
print(x)
print(x.ndim)
print(x.size)

[[[0.65103427 0.36748477 0.07384998 0.24226284 0.28776485 0.32883059
   0.49449431 0.35187542 0.80079351 0.98098365]
  [0.87958668 0.04854294 0.61247746 0.97827686 0.87477265 0.72916453
   0.74032938 0.67135293 0.2136384  0.72789105]
  [0.50356382 0.80316906 0.76266434 0.42823007 0.25062266 0.64219389
   0.85503885 0.9379901  0.80375649 0.1871805 ]
  [0.48378172 0.52108104 0.79643377 0.78278029 0.55054385 0.78842569
   0.72284843 0.44517135 0.46010837 0.5111978 ]
  [0.18612103 0.80276396 0.10793135 0.12637661 0.6033832  0.34901742
   0.23147692 0.75014667 0.5463411  0.61921054]
  [0.37514642 0.36167078 0.18762452 0.3644052  0.59181715 0.77356439
   0.81699796 0.86776129 0.95898699 0.55554255]
  [0.39278293 0.16096996 0.78371142 0.66719062 0.11003591 0.06793865
   0.01958023 0.37015481 0.2197011  0.08316991]
  [0.32739346 0.70863068 0.66555746 0.31415837 0.27034659 0.62234809
   0.6181887  0.91028682 0.97460669 0.45304557]]

 [[0.88585423 0.92614562 0.12057546 0.35121722 0.77572038 0.78

In [5]:
x=np.random.rand(3,7,4)
print(x)
print(x.ndim)
print(x.shape)
print(x.ndim)
print(x.size)

[[[0.94682802 0.84205559 0.82793281 0.41306432]
  [0.80933096 0.55280125 0.52654797 0.83935278]
  [0.99034269 0.49159977 0.97525274 0.25042298]
  [0.19963455 0.05956969 0.41887969 0.00798135]
  [0.29993837 0.21561319 0.01805381 0.38945762]
  [0.02019767 0.59262895 0.47827323 0.22418816]
  [0.19519701 0.834676   0.79514023 0.44634573]]

 [[0.4246545  0.76345603 0.12311832 0.97280555]
  [0.64793159 0.75932652 0.50394672 0.37086922]
  [0.04937048 0.98979367 0.06306283 0.24235836]
  [0.38524256 0.792531   0.31001888 0.82112002]
  [0.58599518 0.44613354 0.47935894 0.81511068]
  [0.71688997 0.6949485  0.08127017 0.90947215]
  [0.44025851 0.24171777 0.11300939 0.31976243]]

 [[0.06588435 0.48310439 0.70064368 0.66669735]
  [0.72605584 0.54110818 0.09456251 0.00499347]
  [0.70462287 0.69303281 0.70806874 0.20682883]
  [0.2093355  0.88835826 0.43513445 0.68935767]
  [0.80737    0.65659556 0.38738073 0.85501898]
  [0.54886559 0.70874165 0.33154869 0.17897467]
  [0.09393679 0.60441463 0.34171418 

In [14]:
x=np.random.rand(5,7,4)
print(x)
print(x.ndim)
print(x.shape)
print(x.size)

[[[0.43954114 0.25145826 0.36493832 0.25791706]
  [0.9891878  0.30325654 0.71449931 0.07013207]
  [0.89639313 0.8076192  0.84968647 0.97458183]
  [0.42150559 0.4952228  0.10723297 0.06384741]
  [0.08443737 0.22942067 0.7174239  0.72993143]
  [0.76485376 0.8415623  0.24046853 0.51319228]
  [0.56558064 0.64761927 0.35419345 0.67115855]]

 [[0.69711748 0.36430505 0.20777751 0.50799904]
  [0.20934026 0.86063719 0.97425015 0.70060927]
  [0.17937446 0.80439464 0.77253662 0.56088811]
  [0.9250841  0.93578904 0.36276125 0.29382493]
  [0.84642721 0.22295367 0.15976582 0.47886606]
  [0.31067692 0.35331088 0.44774246 0.41668636]
  [0.07133151 0.85081387 0.22090321 0.88075212]]

 [[0.45956508 0.03941777 0.57734803 0.24966966]
  [0.01235182 0.51716968 0.31890182 0.0084064 ]
  [0.47428773 0.37879261 0.54761031 0.37804679]
  [0.5259847  0.60321828 0.7380099  0.71656834]
  [0.77831797 0.50819114 0.93378383 0.3805107 ]
  [0.58760806 0.2543931  0.38764774 0.57327292]
  [0.98861762 0.81853283 0.49377435 

In [19]:
#reshape

a=np.arange(48)
print(a)
print(a.ndim)
b=a.reshape(8,6)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47]
1
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]]


In [21]:
a=np.arange(48)
print(a)
print(a.ndim)
b=a.reshape(12,4)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47]
1
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]]


In [27]:
a=np.arange(48)
print(a)
print(a.ndim)
b=a.reshape(6,-1)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47]
1
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47]]


In [29]:
#transpose
a=np.arange(48)
b=a.reshape(6,-1)
c=b.T
print(b)
print(c)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]]
[[ 0  8 16 24 32 40]
 [ 1  9 17 25 33 41]
 [ 2 10 18 26 34 42]
 [ 3 11 19 27 35 43]
 [ 4 12 20 28 36 44]
 [ 5 13 21 29 37 45]
 [ 6 14 22 30 38 46]
 [ 7 15 23 31 39 47]]


In [31]:
#flatten
a=np.arange(48)
b=a.reshape(6,-1)
c=b.T
print(c)
print(c.flatten()) #used in deep learning

[[ 0  8 16 24 32 40]
 [ 1  9 17 25 33 41]
 [ 2 10 18 26 34 42]
 [ 3 11 19 27 35 43]
 [ 4 12 20 28 36 44]
 [ 5 13 21 29 37 45]
 [ 6 14 22 30 38 46]
 [ 7 15 23 31 39 47]]
[ 0  8 16 24 32 40  1  9 17 25 33 41  2 10 18 26 34 42  3 11 19 27 35 43
  4 12 20 28 36 44  5 13 21 29 37 45  6 14 22 30 38 46  7 15 23 31 39 47]


In [32]:
#arithmetic operator
a=np.array([3,1,2,6])
b=np.array([0,1,3,4])
print(a+b)
print(a-b)
print(a*b)
print(a>2)

[ 3  2  5 10]
[ 3  0 -1  2]
[ 0  1  6 24]
[ True False False  True]


In [35]:
a=np.array([[3,6,5],[8,3,6]])
b=np.array([[7,4,9],[9,3,8]])
print('a is',a)
print('b is',b)
print(a+b)
print(a-b)
print(a*b)
print(a>2)

a is [[3 6 5]
 [8 3 6]]
b is [[7 4 9]
 [9 3 8]]
[[10 10 14]
 [17  6 14]]
[[-4  2 -4]
 [-1  0 -2]]
[[21 24 45]
 [72  9 48]]
[[ True  True  True]
 [ True  True  True]]


In [46]:
#dot product
x=np.linspace(1,10,8).reshape(4,2)
print(x)
y=np.linspace(1,10,10).reshape(2,5)
print(y)
z=x.dot(y)
print(z)
print(z.shape)


[[ 1.          2.28571429]
 [ 3.57142857  4.85714286]
 [ 6.14285714  7.42857143]
 [ 8.71428571 10.        ]]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]
[[ 14.71428571  18.          21.28571429  24.57142857  27.85714286]
 [ 32.71428571  41.14285714  49.57142857  58.          66.42857143]
 [ 50.71428571  64.28571429  77.85714286  91.42857143 105.        ]
 [ 68.71428571  87.42857143 106.14285714 124.85714286 143.57142857]]
(4, 5)


In [50]:
x=np.linspace(1,10,8).reshape(4,2,)
y=np.linspace(1,10,10).reshape(2,5)
z=x.dot(y)
print(z)
print(z.shape)

[[ 14.71428571  18.          21.28571429  24.57142857  27.85714286]
 [ 32.71428571  41.14285714  49.57142857  58.          66.42857143]
 [ 50.71428571  64.28571429  77.85714286  91.42857143 105.        ]
 [ 68.71428571  87.42857143 106.14285714 124.85714286 143.57142857]]
(4, 5)


In [54]:
x=np.linspace(1,10,8).reshape(4,2,)
y=np.linspace(1,10,10).reshape(2,5)
z=x.dot(y)
print(z)
print(z.min())
print(z.max())
print(z.sum())
print(z.sum(axis=1)) #row wise sum
print(z.sum(axis=0)) #column wise sum

[[ 14.71428571  18.          21.28571429  24.57142857  27.85714286]
 [ 32.71428571  41.14285714  49.57142857  58.          66.42857143]
 [ 50.71428571  64.28571429  77.85714286  91.42857143 105.        ]
 [ 68.71428571  87.42857143 106.14285714 124.85714286 143.57142857]]
14.714285714285714
143.57142857142858
1274.2857142857144
[106.42857143 247.85714286 389.28571429 530.71428571]
[166.85714286 210.85714286 254.85714286 298.85714286 342.85714286]


In [58]:
#statistical function
x=np.linspace(1,10,8).reshape(4,2)
y=np.linspace(1,10,10).reshape(2,5)
z=x.dot(y)
print(z)
print(np.mean(z))
print(np.var(z))
print(np.median(z))


[[ 14.71428571  18.          21.28571429  24.57142857  27.85714286]
 [ 32.71428571  41.14285714  49.57142857  58.          66.42857143]
 [ 50.71428571  64.28571429  77.85714286  91.42857143 105.        ]
 [ 68.71428571  87.42857143 106.14285714 124.85714286 143.57142857]]
63.71428571428572
1308.2244897959185
61.14285714285715


In [64]:
#Indexing Slicing
x=np.linspace(1,10,8)
print(x)
print(x[5])
print(x[2::2])

[ 1.          2.28571429  3.57142857  4.85714286  6.14285714  7.42857143
  8.71428571 10.        ]
7.428571428571429
[3.57142857 6.14285714 8.71428571]


In [95]:
x=np.linspace(1,10,12).reshape(4,3)
print(x)
#print(x[0][1])
#print(x[0:2,0:2])
#print(x[1::,0::])
print(x[0::,1:2])

[[ 1.          1.81818182  2.63636364]
 [ 3.45454545  4.27272727  5.09090909]
 [ 5.90909091  6.72727273  7.54545455]
 [ 8.36363636  9.18181818 10.        ]]
[[1.81818182]
 [4.27272727]
 [6.72727273]
 [9.18181818]]


In [96]:
x=np.linspace(1,10,36).reshape(9,4)
print(x)


[[ 1.          1.25714286  1.51428571  1.77142857]
 [ 2.02857143  2.28571429  2.54285714  2.8       ]
 [ 3.05714286  3.31428571  3.57142857  3.82857143]
 [ 4.08571429  4.34285714  4.6         4.85714286]
 [ 5.11428571  5.37142857  5.62857143  5.88571429]
 [ 6.14285714  6.4         6.65714286  6.91428571]
 [ 7.17142857  7.42857143  7.68571429  7.94285714]
 [ 8.2         8.45714286  8.71428571  8.97142857]
 [ 9.22857143  9.48571429  9.74285714 10.        ]]


In [102]:
print(x[3::2,1::2])

[[4.34285714 4.85714286]
 [6.4        6.91428571]
 [8.45714286 8.97142857]]


In [109]:
a=np.array([[3,1,2,6],[5,7,2,3],[1,5,2,3]])
print(a)
print(np.argmax(a))
print(np.argmin(a))
print(np.extract(a<4,a))

[[3 1 2 6]
 [5 7 2 3]
 [1 5 2 3]]
5
1
[3 1 2 2 3 1 2 3]
